apiVersion: apps/v1
kind: Deployment
metadata: 
   name: test_deployment1
   labels:
       app: myapp1
       type: front-end
spec:
  replicas: 3
  selector:
     matchLabels: 
       type: front-end
       
  template: 
     metadata:
         name: test_pod1
         labels:
            app: myapp1
            type: front-end
         
     spec: 
        containers:
          - name: nginx-container
            image: nginx
            
     
  
  
     
   
